# Generated by Django 5.0.1 on 2024-01-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('AccessoryId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('NameOfProduct', models.CharField(max_length=255)),
                ('Type', models.CharField(choices=[('Luggage Gear', 'Luggage Gear'), ('Safety Gear', 'Safety Gear'), ('Track Gear', 'Track Gear')], max_length=20)),
                ('Year', models.IntegerField()),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Brand', models.CharField(max_length=255)),
                ('Status', models.CharField(choices=[('On Sale', 'On Sale'), ('Out Of Stock', 'Out Of Stock'), ('Coming Soon', 'Coming Soon')], max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Picture_File_Name', models.CharField(max_length=255)),
            ],
        ),
    ]
