# Generated by Django 5.0.1 on 2024-01-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('BikeId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Type', models.CharField(choices=[('Dirt Bike', 'Dirt Bike'), ('Adventure Bike', 'Adventure Bike'), ('Sports Touring Bike', 'Sports Touring Bike'), ('Sport Bike', 'Sport Bike'), ('Track Bike', 'Track Bike'), ('HyperSport Bike', 'HyperSport Bike')], max_length=20)),
                ('Year', models.IntegerField()),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Brand', models.CharField(max_length=255)),
                ('Status', models.CharField(choices=[('On Sale', 'On Sale'), ('Sold', 'Sold'), ('Coming Soon', 'Coming Soon')], max_length=20)),
                ('Picture_File_Name', models.CharField(max_length=255)),
            ],
        ),
    ]
