# Generated by Django 5.0.1 on 2024-01-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='Type',
            field=models.CharField(choices=[('Dirt Bike', 'Dirt Bike'), ('Adventure Bike', 'Adventure Bike'), ('Sports Touring Bike', 'Sports Touring Bike'), ('Sport Bike', 'Sport Bike'), ('Track Bike', 'Track Bike'), ('HyperSport Bike', 'HyperSport Bike'), ('Naked Bike', 'Naked Bike')], max_length=20),
        ),
    ]
