# Generated by Django 5.0.1 on 2024-01-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255)),
                ('UserEmail', models.EmailField(max_length=255, unique=True)),
                ('UserPassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BikesOrdered',
            fields=[
                ('OrderNumber', models.AutoField(primary_key=True, serialize=False)),
                ('DateOfOrder', models.DateField(auto_now_add=True)),
                ('Bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bikes.bike')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_bikes', to='Users.user')),
            ],
        ),
    ]
