# Generated by Django 5.0.1 on 2024-01-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_useradress_alter_user_userbalance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserBalance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10),
        ),
    ]
