# Generated by Django 5.0.1 on 2024-01-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0001_initial'),
        ('Users', '0005_alter_user_userbalance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bikesordered',
            unique_together={('UserId', 'Bike')},
        ),
    ]
