# Generated by Django 5.0.1 on 2024-01-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_accessoriesordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
