# Generated by Django 5.0.1 on 2024-01-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminId', models.AutoField(primary_key=True, serialize=False)),
                ('AdminEmail', models.CharField(max_length=250, unique=True)),
                ('AdminPassword', models.CharField(max_length=255)),
                ('AdminName', models.CharField(max_length=255)),
                ('AdminType', models.CharField(choices=[('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='Admin', max_length=255)),
            ],
        ),
    ]
